/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.edu.unifei.environment.view;

import br.edu.unifei.environment.dao.ArvoreDao;
import br.edu.unifei.environment.dao.CoelhoDao;
import br.edu.unifei.environment.dao.LoboDao;
import br.edu.unifei.environment.dao.MundoDao;
import br.edu.unifei.environment.dao.SerDao;
import br.edu.unifei.environment.modelo.Animal;
import br.edu.unifei.environment.modelo.Arvore;
import br.edu.unifei.environment.modelo.Coelho;
import br.edu.unifei.environment.modelo.Lobo;
import br.edu.unifei.environment.modelo.Mundo;
import br.edu.unifei.environment.modelo.Ser;
import java.util.ArrayList;
import java.util.List;
import javax.persistence.EntityManager;

/**
 *
 * @author pedro
 */
public class CrudFrame extends javax.swing.JFrame {

    static private ArvoreDao arvoreDao;
    static private MundoDao mundoDao;
    static private CoelhoDao coelhoDao;
    static private LoboDao loboDao;
    static private SerDao serDao;
    static private Mundo m;
    static int updateId;

    /**
     * Creates new form CrudFrame
     */
    public CrudFrame(EntityManager em, MundoDao md, Mundo m, SerDao sd) {
        initComponents();

        arvoreDao = new ArvoreDao(em);
        coelhoDao = new CoelhoDao(em);
        loboDao = new LoboDao(em);
        this.m = m;
        this.mundoDao = md;
        this.serDao = sd;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        jPanel5 = new javax.swing.JPanel();
        jComboBox2 = new javax.swing.JComboBox<>();
        CreatePlantaX = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        CreatePlantaY = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        CreatePlantaVida = new javax.swing.JTextField();
        CreatePlanta = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        CreateAnimalSelect = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        CreateAnimalX = new javax.swing.JTextField();
        CreateAnimalY = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        CreateAnimalFome = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        CreateAnimalMov = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        CreateAnimalVida = new javax.swing.JTextField();
        CreateAnimal = new javax.swing.JButton();
        jLabel17 = new javax.swing.JLabel();
        CreateAnimalAtaque = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        CreateAnimalDesejo = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jTabbedPane3 = new javax.swing.JTabbedPane();
        jPanel7 = new javax.swing.JPanel();
        BuscarPlantaCombo = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        BuscarPlantaList = new javax.swing.JList<>();
        BuscarPlanta = new javax.swing.JButton();
        jPanel8 = new javax.swing.JPanel();
        ReadAnimalCombo = new javax.swing.JComboBox<>();
        ReadAnimal = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        ReadAnimalList = new javax.swing.JList<>();
        jPanel3 = new javax.swing.JPanel();
        jTabbedPane4 = new javax.swing.JTabbedPane();
        jPanel11 = new javax.swing.JPanel();
        UpdatePlantaCombo = new javax.swing.JComboBox<>();
        UpdatePlantaX = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        UpdatePlantaY = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        UpdatePlantaVida = new javax.swing.JTextField();
        UpdatePlanta = new javax.swing.JButton();
        UpdatePlantaButton = new javax.swing.JButton();
        jPanel12 = new javax.swing.JPanel();
        UpdateAnimalCombo = new javax.swing.JComboBox<>();
        jLabel22 = new javax.swing.JLabel();
        UpdateAnimalX = new javax.swing.JTextField();
        UpdateAnimalY = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        UpdateAnimalFome = new javax.swing.JTextField();
        jLabel25 = new javax.swing.JLabel();
        UpdateAnimalMov = new javax.swing.JTextField();
        jLabel26 = new javax.swing.JLabel();
        UpdateAnimalVida = new javax.swing.JTextField();
        UpdateAnimal = new javax.swing.JButton();
        jLabel27 = new javax.swing.JLabel();
        UpdateAnimalAtk = new javax.swing.JTextField();
        jLabel28 = new javax.swing.JLabel();
        UpdateAnimalDes = new javax.swing.JTextField();
        UpdateAnimalButton = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        DeleteList = new javax.swing.JList<>();
        DeleteButton = new javax.swing.JButton();
        DeleteRefresh = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("CRUD");

        jTabbedPane1.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jTabbedPane1StateChanged(evt);
            }
        });

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Arvore" }));

        CreatePlantaX.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CreatePlantaXActionPerformed(evt);
            }
        });

        jLabel1.setText("X:");

        jLabel2.setText("Y:");

        jLabel3.setText("Vida:");

        CreatePlantaVida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CreatePlantaVidaActionPerformed(evt);
            }
        });

        CreatePlanta.setText("Create");
        CreatePlanta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CreatePlantaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jComboBox2, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(CreatePlantaX, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 49, Short.MAX_VALUE)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(CreatePlantaY, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(CreatePlantaVida, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(CreatePlanta, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CreatePlantaX, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(CreatePlantaY, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(20, 20, 20)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CreatePlantaVida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 147, Short.MAX_VALUE)
                .addComponent(CreatePlanta, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jTabbedPane2.addTab("Planta", jPanel5);

        CreateAnimalSelect.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Coelho", "Lobo" }));

        jLabel4.setText("X:");

        CreateAnimalX.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CreateAnimalXActionPerformed(evt);
            }
        });

        jLabel5.setText("Y:");

        jLabel7.setText("Fome:");

        CreateAnimalFome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CreateAnimalFomeActionPerformed(evt);
            }
        });

        jLabel8.setText("Mov:");

        jLabel9.setText("Vida:");

        CreateAnimalVida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CreateAnimalVidaActionPerformed(evt);
            }
        });

        CreateAnimal.setText("Create");
        CreateAnimal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CreateAnimalActionPerformed(evt);
            }
        });

        jLabel17.setText("Atk:");

        CreateAnimalAtaque.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CreateAnimalAtaqueActionPerformed(evt);
            }
        });

        jLabel18.setText("Des:");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(98, 98, 98)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(CreateAnimalVida, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(CreateAnimalSelect, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel6Layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(CreateAnimalFome))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel6Layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(CreateAnimalX, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(CreateAnimalY, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(CreateAnimalMov, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(CreateAnimal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jLabel17)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(CreateAnimalAtaque)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel18)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(CreateAnimalDesejo, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(CreateAnimalSelect, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CreateAnimalX, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(CreateAnimalY, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CreateAnimalFome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(CreateAnimalMov, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 43, Short.MAX_VALUE)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CreateAnimalAtaque, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel17)
                    .addComponent(CreateAnimalDesejo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel18))
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CreateAnimalVida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addGap(36, 36, 36)
                .addComponent(CreateAnimal, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jTabbedPane2.addTab("Animal", jPanel6);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane2)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane2)
        );

        jTabbedPane1.addTab("Create", jPanel1);

        BuscarPlantaCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Todos", "Arvore" }));

        jScrollPane1.setViewportView(BuscarPlantaList);

        BuscarPlanta.setText("Buscar");
        BuscarPlanta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BuscarPlantaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(BuscarPlantaCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(BuscarPlanta, javax.swing.GroupLayout.DEFAULT_SIZE, 109, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BuscarPlantaCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BuscarPlanta))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 292, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane3.addTab("Planta", jPanel7);

        ReadAnimalCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Todos", "Coelho", "Lobo" }));

        ReadAnimal.setText("Buscar");
        ReadAnimal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ReadAnimalActionPerformed(evt);
            }
        });

        jScrollPane3.setViewportView(ReadAnimalList);

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addComponent(ReadAnimalCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ReadAnimal, javax.swing.GroupLayout.DEFAULT_SIZE, 109, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ReadAnimalCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ReadAnimal))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 292, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane3.addTab("Animal", jPanel8);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane3)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane3)
        );

        jTabbedPane1.addTab("Read", jPanel2);

        UpdatePlantaCombo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                UpdatePlantaComboMouseClicked(evt);
            }
        });
        UpdatePlantaCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdatePlantaComboActionPerformed(evt);
            }
        });

        UpdatePlantaX.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdatePlantaXActionPerformed(evt);
            }
        });

        jLabel19.setText("X:");

        jLabel20.setText("Y:");

        jLabel21.setText("Vida:");

        UpdatePlantaVida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdatePlantaVidaActionPerformed(evt);
            }
        });

        UpdatePlanta.setText("Update");
        UpdatePlanta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdatePlantaActionPerformed(evt);
            }
        });

        UpdatePlantaButton.setText("Atualizar");
        UpdatePlantaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdatePlantaButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel11Layout.createSequentialGroup()
                        .addComponent(jLabel19)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(UpdatePlantaX, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 49, Short.MAX_VALUE)
                        .addComponent(jLabel20)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(UpdatePlantaY, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(UpdatePlanta, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel11Layout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addComponent(jLabel21)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(UpdatePlantaVida, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel11Layout.createSequentialGroup()
                        .addComponent(UpdatePlantaCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 277, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(UpdatePlantaButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(UpdatePlantaCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(UpdatePlantaButton))
                .addGap(18, 18, 18)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(UpdatePlantaX, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel19)
                    .addComponent(UpdatePlantaY, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel20))
                .addGap(20, 20, 20)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(UpdatePlantaVida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel21))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 145, Short.MAX_VALUE)
                .addComponent(UpdatePlanta, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jTabbedPane4.addTab("Planta", jPanel11);

        UpdateAnimalCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdateAnimalComboActionPerformed(evt);
            }
        });

        jLabel22.setText("X:");

        UpdateAnimalX.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdateAnimalXActionPerformed(evt);
            }
        });

        jLabel23.setText("Y:");

        jLabel24.setText("Fome:");

        UpdateAnimalFome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdateAnimalFomeActionPerformed(evt);
            }
        });

        jLabel25.setText("Mov:");

        jLabel26.setText("Vida:");

        UpdateAnimalVida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdateAnimalVidaActionPerformed(evt);
            }
        });

        UpdateAnimal.setText("Update");
        UpdateAnimal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdateAnimalActionPerformed(evt);
            }
        });

        jLabel27.setText("Atk:");

        UpdateAnimalAtk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdateAnimalAtkActionPerformed(evt);
            }
        });

        jLabel28.setText("Des:");

        UpdateAnimalButton.setText("Atualizar");
        UpdateAnimalButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdateAnimalButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addGap(98, 98, 98)
                .addComponent(jLabel26)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(UpdateAnimalVida, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel12Layout.createSequentialGroup()
                        .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel12Layout.createSequentialGroup()
                                .addComponent(jLabel24)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(UpdateAnimalFome))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel12Layout.createSequentialGroup()
                                .addComponent(jLabel22)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(UpdateAnimalX, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                        .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel12Layout.createSequentialGroup()
                                .addComponent(jLabel23)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(UpdateAnimalY, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel12Layout.createSequentialGroup()
                                .addComponent(jLabel25)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(UpdateAnimalMov, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(UpdateAnimal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel12Layout.createSequentialGroup()
                        .addComponent(jLabel27)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(UpdateAnimalAtk)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel28)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(UpdateAnimalDes, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel12Layout.createSequentialGroup()
                        .addComponent(UpdateAnimalCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 277, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(UpdateAnimalButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(UpdateAnimalCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(UpdateAnimalButton))
                .addGap(18, 18, 18)
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(UpdateAnimalX, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel22)
                    .addComponent(UpdateAnimalY, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel23))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(UpdateAnimalFome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel24)
                    .addComponent(UpdateAnimalMov, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel25))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(UpdateAnimalAtk, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel27)
                    .addComponent(UpdateAnimalDes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel28))
                .addGap(18, 18, 18)
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(UpdateAnimalVida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel26))
                .addGap(36, 36, 36)
                .addComponent(UpdateAnimal, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jTabbedPane4.addTab("Animal", jPanel12);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane4)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane4)
        );

        jTabbedPane1.addTab("Update", jPanel3);

        jScrollPane2.setViewportView(DeleteList);

        DeleteButton.setBackground(new java.awt.Color(228, 98, 61));
        DeleteButton.setText("Deletar");
        DeleteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteButtonActionPerformed(evt);
            }
        });

        DeleteRefresh.setText("Atualizar");
        DeleteRefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteRefreshActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(DeleteRefresh, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(DeleteButton, javax.swing.GroupLayout.DEFAULT_SIZE, 401, Short.MAX_VALUE)
                    .addComponent(jScrollPane2))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addComponent(DeleteRefresh, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 230, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(DeleteButton, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Delete", jPanel4);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTabbedPane1StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jTabbedPane1StateChanged


    }//GEN-LAST:event_jTabbedPane1StateChanged

    private void CreatePlantaXActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CreatePlantaXActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CreatePlantaXActionPerformed

    private void CreatePlantaVidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CreatePlantaVidaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CreatePlantaVidaActionPerformed

    private void CreateAnimalXActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CreateAnimalXActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CreateAnimalXActionPerformed

    private void CreateAnimalFomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CreateAnimalFomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CreateAnimalFomeActionPerformed

    private void CreateAnimalVidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CreateAnimalVidaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CreateAnimalVidaActionPerformed

    private void CreatePlantaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CreatePlantaActionPerformed
        Arvore a = new Arvore();
        a.setX(Integer.parseInt(CreatePlantaX.getText()));
        a.setY(Integer.parseInt(CreatePlantaY.getText()));
        a.setVida(Integer.parseInt(CreatePlantaVida.getText()));

        System.out.println("dsa " + this.m.getSeres().size());

        this.m.addSer(a);
        this.mundoDao.update(this.m);
    }//GEN-LAST:event_CreatePlantaActionPerformed

    private void CreateAnimalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CreateAnimalActionPerformed
        if (CreateAnimalSelect.getSelectedIndex() == 0) {
            Coelho c = new Coelho();
            c.setX(Integer.parseInt(CreateAnimalX.getText()));
            c.setY(Integer.parseInt(CreateAnimalY.getText()));
            c.setVida(Integer.parseInt(CreateAnimalVida.getText()));
            c.setAtaque(Integer.parseInt(CreateAnimalAtaque.getText()));
            c.setFome(Integer.parseInt(CreateAnimalFome.getText()));
            c.setMovimento(Integer.parseInt(CreateAnimalMov.getText()));
            c.setDesejo(Integer.parseInt(CreateAnimalDesejo.getText()));

            this.m.addSer(c);

        } else {
            Lobo l = new Lobo();
            l.setX(Integer.parseInt(CreateAnimalX.getText()));
            l.setY(Integer.parseInt(CreateAnimalY.getText()));
            l.setVida(Integer.parseInt(CreateAnimalVida.getText()));
            l.setAtaque(Integer.parseInt(CreateAnimalAtaque.getText()));
            l.setFome(Integer.parseInt(CreateAnimalFome.getText()));
            l.setMovimento(Integer.parseInt(CreateAnimalMov.getText()));
            l.setDesejo(Integer.parseInt(CreateAnimalDesejo.getText()));

            this.m.addSer(l);
        }
        this.mundoDao.update(this.m);
    }//GEN-LAST:event_CreateAnimalActionPerformed

    private void CreateAnimalAtaqueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CreateAnimalAtaqueActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CreateAnimalAtaqueActionPerformed

    private void BuscarPlantaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BuscarPlantaActionPerformed
        List<String> arvoreInstaceList = new ArrayList<>();

        this.arvoreDao.findAll().forEach(arvore -> {
            arvoreInstaceList.add(arvore.getId() + "   <X: " + arvore.getX() + " Y: "
                    + arvore.getY() + " VIDA " + arvore.getVida() + ">");
        });

        String[] arvoreInstanceString = new String[arvoreInstaceList.size()];
        BuscarPlantaList.setListData(arvoreInstaceList.toArray(arvoreInstanceString));
    }//GEN-LAST:event_BuscarPlantaActionPerformed

    private void ReadAnimalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ReadAnimalActionPerformed
        List<String> animalInstanceList = new ArrayList<>();

        if (ReadAnimalCombo.getSelectedIndex() == 0) {
            this.coelhoDao.findAll().forEach(coelho -> {
                animalInstanceList.add("(COELHO) " + coelho.getId() + "   <X: " + coelho.getX() + " Y: "
                        + coelho.getY() + " VIDA: " + coelho.getVida()
                        + " FOME: " + coelho.getFome() + " DES: " + coelho.getDesejo()
                        + " MOV: " + coelho.getMovimento() + " ATK: " + coelho.getAtaque() + ">");
            });

            this.loboDao.findAll().forEach(lobo -> {
                animalInstanceList.add("(LOBO) " + lobo.getId() + "   <X: " + lobo.getX() + " Y: "
                        + lobo.getY() + " VIDA: " + lobo.getVida()
                        + " FOME: " + lobo.getFome() + " DES: " + lobo.getDesejo()
                        + " MOV: " + lobo.getMovimento() + " ATK: " + lobo.getAtaque() + ">");
            });
        } else if (ReadAnimalCombo.getSelectedIndex() == 1) {
            this.coelhoDao.findAll().forEach(coelho -> {
                animalInstanceList.add(coelho.getId() + "   <X: " + coelho.getX() + " Y: "
                        + coelho.getY() + " VIDA: " + coelho.getVida()
                        + " FOME: " + coelho.getFome() + " DES: " + coelho.getDesejo()
                        + " MOV: " + coelho.getMovimento() + " ATK: " + coelho.getAtaque() + ">");
            });
        } else if (ReadAnimalCombo.getSelectedIndex() == 2) {
            this.loboDao.findAll().forEach(lobo -> {
                animalInstanceList.add(lobo.getId() + "   <X: " + lobo.getX() + " Y: "
                        + lobo.getY() + " VIDA: " + lobo.getVida()
                        + " FOME: " + lobo.getFome() + " DES: " + lobo.getDesejo()
                        + " MOV: " + lobo.getMovimento() + " ATK: " + lobo.getAtaque() + ">");
            });
        }

        String[] arvoreInstanceString = new String[animalInstanceList.size()];
        ReadAnimalList.setListData(animalInstanceList.toArray(arvoreInstanceString));
    }//GEN-LAST:event_ReadAnimalActionPerformed

    private void UpdatePlantaXActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdatePlantaXActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_UpdatePlantaXActionPerformed

    private void UpdatePlantaVidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdatePlantaVidaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_UpdatePlantaVidaActionPerformed

    private void UpdatePlantaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdatePlantaActionPerformed
        updateId = Integer.parseInt(UpdatePlantaCombo.getSelectedItem().toString());

        for (Ser ser : this.m.getSeres()) {
            if (ser.getId() == updateId) {
                ser.setX(Integer.parseInt(UpdatePlantaX.getText()));
                ser.setY(Integer.parseInt(UpdatePlantaY.getText()));
                ser.setVida(Integer.parseInt(UpdatePlantaVida.getText()));
            }
        };

        this.mundoDao.update(this.m);
    }//GEN-LAST:event_UpdatePlantaActionPerformed

    private void UpdateAnimalXActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdateAnimalXActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_UpdateAnimalXActionPerformed

    private void UpdateAnimalFomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdateAnimalFomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_UpdateAnimalFomeActionPerformed

    private void UpdateAnimalVidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdateAnimalVidaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_UpdateAnimalVidaActionPerformed

    private void UpdateAnimalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdateAnimalActionPerformed
        updateId = Integer.parseInt(UpdateAnimalCombo.getSelectedItem().toString());

        for (Ser serAux : this.m.getSeres()) {
            if (serAux.getId() == updateId) {
                Animal ser = (Animal) serAux;

                ser.setX(Integer.parseInt(UpdateAnimalX.getText()));
                ser.setY(Integer.parseInt(UpdateAnimalY.getText()));
                ser.setAtaque(Integer.parseInt(UpdateAnimalAtk.getText()));
                ser.setDesejo(Integer.parseInt(UpdateAnimalDes.getText()));
                ser.setFome(Integer.parseInt(UpdateAnimalFome.getText()));
                ser.setMovimento(Integer.parseInt(UpdateAnimalMov.getText()));
                ser.setVida(Integer.parseInt(UpdateAnimalVida.getText()));

            }
        };

        this.mundoDao.update(this.m);
    }//GEN-LAST:event_UpdateAnimalActionPerformed

    private void UpdateAnimalAtkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdateAnimalAtkActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_UpdateAnimalAtkActionPerformed

    private void UpdatePlantaComboMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_UpdatePlantaComboMouseClicked
        System.out.println("DASDASDS");        // TODO add your handling code here:
    }//GEN-LAST:event_UpdatePlantaComboMouseClicked

    private void UpdatePlantaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdatePlantaButtonActionPerformed
        UpdatePlantaCombo.removeAllItems();

        this.arvoreDao.findAll().forEach(arvore -> {
            UpdatePlantaCombo.addItem(Integer.toString(arvore.getId()));
        });        // TODO add your handling code here:
    }//GEN-LAST:event_UpdatePlantaButtonActionPerformed

    private void UpdatePlantaComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdatePlantaComboActionPerformed
        updateId = Integer.parseInt(UpdatePlantaCombo.getSelectedItem().toString());

        this.m.getSeres().forEach(ser -> {
            if (ser.getId() == updateId) {
                UpdatePlantaX.setText(Integer.toString(ser.getX()));
                UpdatePlantaY.setText(Integer.toString(ser.getY()));
                UpdatePlantaVida.setText(Integer.toString(ser.getVida()));
            }
        });
    }//GEN-LAST:event_UpdatePlantaComboActionPerformed

    private void UpdateAnimalButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdateAnimalButtonActionPerformed
        UpdateAnimalCombo.removeAllItems();

        this.coelhoDao.findAll().forEach(coelho -> {
            UpdateAnimalCombo.addItem(Integer.toString(coelho.getId()));
        });

        this.loboDao.findAll().forEach(lobo -> {
            UpdateAnimalCombo.addItem(Integer.toString(lobo.getId()));
        });
    }//GEN-LAST:event_UpdateAnimalButtonActionPerformed

    private void UpdateAnimalComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdateAnimalComboActionPerformed
        updateId = Integer.parseInt(UpdateAnimalCombo.getSelectedItem().toString());

        this.m.getSeres().forEach(serAux -> {
            if (serAux.getId() == updateId) {
                Animal ser = (Animal) serAux;
                UpdateAnimalX.setText(Integer.toString(ser.getX()));
                UpdateAnimalY.setText(Integer.toString(ser.getY()));
                UpdateAnimalAtk.setText(Integer.toString(ser.getAtaque()));
                UpdateAnimalDes.setText(Integer.toString(ser.getDesejo()));
                UpdateAnimalFome.setText(Integer.toString(ser.getFome()));
                UpdateAnimalMov.setText(Integer.toString(ser.getMovimento()));
                UpdateAnimalVida.setText(Integer.toString(ser.getVida()));
            }
        });
    }//GEN-LAST:event_UpdateAnimalComboActionPerformed

    private void DeleteRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteRefreshActionPerformed
        List<String> serList = new ArrayList<>();

        this.serDao.findAll().forEach(ser -> {
            String classe = ser.getClass().getName().substring(ser.getClass().getName().indexOf("modelo") + 7);

            serList.add("(" + classe + ") ID: " + ser.getId() + "   <X: " + ser.getX() + " Y: "
                    + ser.getY() + " VIDA " + ser.getVida() + ">");
        });

        String[] serStringList = new String[serList.size()];
        DeleteList.setListData(serList.toArray(serStringList));
    }//GEN-LAST:event_DeleteRefreshActionPerformed

    private void DeleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteButtonActionPerformed
        int serId
                = Integer.parseInt(DeleteList.getSelectedValue().substring(
                        DeleteList.getSelectedValue().indexOf("ID: ") + 4,
                        DeleteList.getSelectedValue().indexOf("   <X:")
                ));

        for (Ser ser : this.m.getSeres()) {
            if (ser.getId() == serId) {
                this.m.getSeres().remove(ser);
            }
        }

        this.mundoDao.update(this.m);
        this.DeleteRefreshActionPerformed(null);
    }//GEN-LAST:event_DeleteButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CrudFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CrudFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CrudFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CrudFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BuscarPlanta;
    private javax.swing.JComboBox<String> BuscarPlantaCombo;
    private javax.swing.JList<String> BuscarPlantaList;
    private javax.swing.JButton CreateAnimal;
    private javax.swing.JTextField CreateAnimalAtaque;
    private javax.swing.JTextField CreateAnimalDesejo;
    private javax.swing.JTextField CreateAnimalFome;
    private javax.swing.JTextField CreateAnimalMov;
    private javax.swing.JComboBox<String> CreateAnimalSelect;
    private javax.swing.JTextField CreateAnimalVida;
    private javax.swing.JTextField CreateAnimalX;
    private javax.swing.JTextField CreateAnimalY;
    private javax.swing.JButton CreatePlanta;
    private javax.swing.JTextField CreatePlantaVida;
    private javax.swing.JTextField CreatePlantaX;
    private javax.swing.JTextField CreatePlantaY;
    private javax.swing.JButton DeleteButton;
    private javax.swing.JList<String> DeleteList;
    private javax.swing.JButton DeleteRefresh;
    private javax.swing.JButton ReadAnimal;
    private javax.swing.JComboBox<String> ReadAnimalCombo;
    private javax.swing.JList<String> ReadAnimalList;
    private javax.swing.JButton UpdateAnimal;
    private javax.swing.JTextField UpdateAnimalAtk;
    private javax.swing.JButton UpdateAnimalButton;
    private javax.swing.JComboBox<String> UpdateAnimalCombo;
    private javax.swing.JTextField UpdateAnimalDes;
    private javax.swing.JTextField UpdateAnimalFome;
    private javax.swing.JTextField UpdateAnimalMov;
    private javax.swing.JTextField UpdateAnimalVida;
    private javax.swing.JTextField UpdateAnimalX;
    private javax.swing.JTextField UpdateAnimalY;
    private javax.swing.JButton UpdatePlanta;
    private javax.swing.JButton UpdatePlantaButton;
    private javax.swing.JComboBox<String> UpdatePlantaCombo;
    private javax.swing.JTextField UpdatePlantaVida;
    private javax.swing.JTextField UpdatePlantaX;
    private javax.swing.JTextField UpdatePlantaY;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JTabbedPane jTabbedPane3;
    private javax.swing.JTabbedPane jTabbedPane4;
    // End of variables declaration//GEN-END:variables
}
